# .Xdefaults

cat > "$HOME/.Xdefaults" <<"EOF"
xterm*background: black
xterm*foreground: white
xterm*faceName: Fira Code:pixelsize=14:antialias=true

! Solarized, generated by terminal.sexy
*.foreground:   #93a1a1
*.background:   #002b36
*.cursorColor:  #93a1a1
*.color0:       #002b36
*.color8:       #657b83
*.color1:       #dc322f
*.color9:       #dc322f
*.color2:       #859900
*.color10:      #859900
*.color3:       #b58900
*.color11:      #b58900
*.color4:       #268bd2
*.color12:      #268bd2
*.color5:       #6c71c4
*.color13:      #6c71c4
*.color6:       #2aa198
*.color14:      #2aa198
*.color7:       #93a1a1
*.color15:      #fdf6e3
EOF
