# .Xdefaults

cat > "$HOME/.Xdefaults" <<"EOF"
*faceName: Fira Code:style=Medium:antialias=true
*faceSize1: 8
*faceSize2: 10
*faceSize3: 12
*faceSize: 12
*faceSize4: 14
*faceSize5: 16
*faceSize6: 18
*allowBoldFonts: false

! Solarized dark, generated by terminal.sexy
! *background: black
! *foreground: #c3c9c9
! *.cursorColor:  #93a1a1
! *.color0:       #002b36
! *.color8:       #657b83
! *.color1:       #dc322f
! *.color9:       #dc322f
! *.color2:       #859900
! *.color10:      #859900
! *.color3:       #b58900
! *.color11:      #b58900
! *.color4:       #268bd2
! *.color12:      #268bd2
! *.color5:       #6c71c4
! *.color13:      #6c71c4
! *.color6:       #2aa198
! *.color14:      #2aa198
! *.color7:       #93a1a1
! *.color15:      #fdf6e3

! Solarized light, generated by terminal.sexy
*foreground: #2d393c
*background: #fdf6e3
*.cursorColor:  #586e75
*.color0:       #002b36
*.color8:       #657b83
*.color1:       #dc322f
*.color9:       #dc322f
*.color2:       #859900
*.color10:      #859900
*.color3:       #b58900
*.color11:      #b58900
*.color4:       #268bd2
*.color12:      #268bd2
*.color5:       #6c71c4
*.color13:      #6c71c4
*.color6:       #2aa198
*.color14:      #2aa198
*.color7:       #93a1a1
*.color15:      #fdf6e3

XTerm.vt100.translations: #override \n\
	Alt <Key> minus: smaller-vt-font() \n\
	Alt <Key> equal: larger-vt-font()
EOF
